---
#########
##DplyR##
#########
---

```{r}
library(tidyverse)
```

```{r}
flights <- read_csv("datos_originales/flights.csv")
```

## filter()

```{r}
filter(flights, month == 1, day == 1) #seleccionando aquellos vuelos del primero de enero
ene1 <- filter(flights, month == 1, day == 1) #asignandolos a una variable
filter(flights, arr_delay >= 120) #Vuelos con atraso en la llegada superior a dos horas
```

### Vuelos operados por United, American, or Delta
```{r}
(airlines <- read_csv("datos_originales/airlines.csv")) #necesitamos un poco más de información
filter(flights, carrier == "AA" | carrier == "DL"| carrier == "UA")
filter(flights, carrier %in% c("AA", "DL", "UA")) #otra forma de hacer lo mismo
```

## arrange()

```{r}
arrange(flights, year, month, day) #ordenar por año, luego por mes, y luego por día
arrange(flights, dep_delay) #ordenar en forma ascendente por atraso en despegue
arrange(flights, desc(dep_delay)) #ordenar en forma descendente por atraso en despegue
```

## select()

```{r}
select(flights, year, month, day) #reduce a tres columnas la base de datos
select(flights, year:day) #lo mismo que el caso anterior seleccionando columnas entre year y day incluidas
select(flights, -(year:day)) #seleccionar todas las columnas menos aquellas entre year y day, incluidas
```

### select() con starts_with(), ends_with(), y contains()

```{r}
select(flights, tailnum, starts_with("arr")) #ver informaci?n de aterrizajes
select(flights, tailnum, ends_with("delay")) #informaci?n de atrasos
select(flights, tailnum, contains("_")) #seleccionar todas las variables que se separan por "_"
```

### everything()

```{r}
#select también sirve para ordenar variables
select(flights, time_hour, air_time, everything()) #asignando las tres primeras columnas y luego manteniendo el resto
```

### rename()

```{r}
rename(flights, 
       tail_num = tailnum) #nombre nuevo = nombre viejo
```

##mutate()

```{r}
#creando una base de datos más chica (menos columnas)
flights_sml <- select(flights, 
                      tailnum,
                      ends_with("delay"), 
                      distance, 
                      air_time) 
```


```{r}
mutate(flights_sml,
       ganancia = dep_delay - arr_delay,
       velocidad = distance / air_time * 60) #creando dos nuevas variables
```

```{r}
#se pueden utilizar las mismas variables que ya se est?n creando (ver ganancia)
mutate(flights_sml,
       ganancia = dep_delay - arr_delay,
       horas = air_time / 60,
       ganancia_por_hora = ganancia / horas)
```

```{r}
#transmute solo deja las nuevas variables creadas
transmute(flights,
           ganancia = dep_delay - arr_delay,
           horas = air_time / 60,
           ganancia_por_hora = ganancia / horas)
```

##summarise()

```{r}
#calcular el promedio de atrasos de despegue
summarise(flights, 
          atraso = mean(dep_delay, na.rm = TRUE))
```

#group_by()

```{r}
#calcular el promedio de atrasos de despegue para cada mes
summarise(group_by(flights, month), atraso = mean(dep_delay, na.rm = TRUE)) 
```


